export const GET_RESTAURANTS_FOR_GEO_SUCCESS = 'GET_RESTAURANTS_FOR_GEO_SUCCESS';
export const RETRIEVED_GEOLOCATION_SUCCESSFULLY = 'RETRIEVED_GEOLOCATION_SUCCESSFULLY';
export const RETRIEVED_GEOLOCATION_FAILED = 'RETRIEVED_GEOLOCATION_FAILED';
